version: '3'

services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: master
    command: /opt/spark-2.4.4-bin-hadoop2.7/bin/spark-class org.apache.spark.deploy.master.Master -h master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /opt/spark-2.4.4-bin-hadoop2.7/conf
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 4040:4040
      - 8080:8080
    volumes:
      - .:/work/spark-demo

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: worker
    command: /opt/spark-2.4.4-bin-hadoop2.7/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    environment:
      SPARK_CONF_DIR: /opt/spark-2.4.4-bin-hadoop2.7/conf
      SPARK_PUBLIC_DNS: localhost
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    ports:
      - 8081-8089:8081
    volumes:
      - .:/work/spark-demo
    links:
      - master
